[workspace]
resolver = "2"
members = [
  "example/derive_expression/expression_lib",
  "example/extend_polars_python_dispatch/extend_polars",
  "pyo3-polars",
  "pyo3-polars-derive",
]

[workspace.dependencies]
polars =      {git = "https://github.com/pola-rs/polars", branch = "plugin", version = "0.33.2", default-features = false }
polars-core = {git = "https://github.com/pola-rs/polars", branch = "plugin",version = "0.33.2", default-features = false }
polars-ffi =  {git = "https://github.com/pola-rs/polars", branch = "plugin", version = "0.33.2", default-features = false }
polars-plan = {git = "https://github.com/pola-rs/polars", branch = "plugin", version = "0.33.2", default-feautres = false }
polars-lazy = {git = "https://github.com/pola-rs/polars", branch = "plugin", version = "0.33.2", default-features = false }
